import React, { useState, useEffect } from "react";
import {
    getSalesReport,
    getCustomers,
    getItems
} from "./salesService";

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import { saveAs } from "file-saver";

const SalesReportPage = () => {
    const [fromDate, setFromDate] = useState("");
    const [toDate, setToDate] = useState("");
    const [customerId, setCustomerId] = useState("");
    const [itemId, setItemId] = useState("");

    const [customers, setCustomers] = useState([]);
    const [items, setItems] = useState([]);
    const [data, setData] = useState([]);
    const [summary, setSummary] = useState({
        totalBills: 0,
        totalQuantity: 0,
        totalAmount: 0,
        averageBillAmount: 0
    });
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState("");

    const [currentPage, setCurrentPage] = useState(1);
    const recordsPerPage = 10;

    useEffect(() => {
        loadDropdowns();
    }, []);

    const loadDropdowns = async () => {
        try {
            const [customersData, itemsData] = await Promise.all([
                getCustomers(),
                getItems()
            ]);
            setCustomers(customersData || []);
            setItems(itemsData || []);
        } catch (err) {
            console.error("Error loading dropdowns:", err);
        }
    };

    const handleGenerate = async () => {
        if (!fromDate || !toDate) {
            alert("Select date range");
            return;
        }

        setLoading(true);
        setError("");

        try {
            const response = await getSalesReport(
                fromDate,
                toDate,
                customerId || null,
                itemId || null
            );

            setData(response.transactions || []);
            setSummary(response.summary || {
                totalBills: 0,
                totalQuantity: 0,
                totalAmount: 0,
                averageBillAmount: 0
            });
            setCurrentPage(1);
        } catch (err) {
            setError(err.response?.data?.error || "Failed to generate report");
            console.error(err);
        } finally {
            setLoading(false);
        }
    };

    // Pagination
    const indexOfLast = currentPage * recordsPerPage;
    const indexOfFirst = indexOfLast - recordsPerPage;
    const currentRecords = data.slice(indexOfFirst, indexOfLast);
    const totalPages = Math.ceil(data.length / recordsPerPage);

    const exportPDF = () => {
        const doc = new jsPDF("landscape");
        const pageWidth = doc.internal.pageSize.getWidth();

        const companyName = "ABC Company Pvt Ltd";
        const branchName = "Main Branch";
        const loginUser = "admin";
        const generatedOn = new Date().toLocaleString();

        const customerFilter = customerId
            ? customers.find(c => c.id == customerId)?.name
            : "All Customers";
        const itemFilter = itemId
            ? items.find(i => i.id == itemId)?.name
            : "All Items";

        // Header
        doc.setFontSize(18);
        doc.text(companyName, pageWidth / 2, 15, { align: "center" });
        doc.setFontSize(14);
        doc.text("Sales Report", pageWidth / 2, 25, { align: "center" });

        doc.setFontSize(10);
        doc.text(`Branch: ${branchName}`, 14, 35);
        doc.text(`Date Range: ${fromDate} to ${toDate}`, 14, 42);
        doc.text(`Generated By: ${loginUser}`, 14, 49);
        doc.text(`Generated On: ${generatedOn}`, 14, 56);
        doc.text(`Customer: ${customerFilter}`, pageWidth - 14, 42, { align: "right" });
        doc.text(`Item: ${itemFilter}`, pageWidth - 14, 49, { align: "right" });

        // Summary
        doc.setFontSize(9);
        doc.text(`Total Bills: ${summary.totalBills}`, 14, 65);
        doc.text(`Total Qty: ${summary.totalQuantity.toFixed(2)}`, 14, 72);
        doc.text(`Total Amount: Rs. ${summary.totalAmount.toFixed(2)}`, 14, 79);
        doc.text(`Avg Bill: Rs. ${summary.averageBillAmount.toFixed(2)}`, 14, 86);

        // Table
        autoTable(doc, {
            startY: 95,
            head: [["Date", "Bill #", "Customer", "Item", "Model", "Qty", "Rate", "Amount", "Bill Total", "Remarks"]],
            body: data.map(r => [
                r.saleDate,
                r.billNo,
                r.customerName,
                r.itemName,
                r.modlNumb,
                r.quantity?.toFixed(2),
                r.rate?.toFixed(2),
                r.amount?.toFixed(2),
                r.billTotal?.toFixed(2),
                r.description
            ]),
            foot: [[
                "TOTALS", "", "", "", "",
                { content: summary.totalQuantity.toFixed(2), styles: { halign: 'right' } },
                "",
                { content: summary.totalAmount.toFixed(2), styles: { halign: 'right' } },
                "", ""
            ]],
            theme: "grid",
            styles: { fontSize: 7 },
            headStyles: { fillColor: [40, 40, 40] },
            footStyles: {
                fillColor: [40, 40, 40],
                textColor: [255, 255, 255],
                fontStyle: 'bold'
            },
            columnStyles: {
                5: { halign: 'right' }, // Qty
                6: { halign: 'right' }, // Rate
                7: { halign: 'right' }, // Amount
                8: { halign: 'right' }, // Bill Total
            }
        });

        // Page numbers
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.text(
                `Page ${i} of ${pageCount}`,
                pageWidth - 20,
                doc.internal.pageSize.getHeight() - 10
            );
        }

        doc.save(`SalesReport_${fromDate}_to_${toDate}.pdf`);
    };

    const exportExcel = () => {
        const worksheet = XLSX.utils.json_to_sheet(data.map(r => ({
            Date: r.saleDate,
            "Bill #": r.billNo,
            Customer: r.customerName,
            Item: r.itemName,
            Model: r.modlNumb,
            Quantity: r.quantity,
            Rate: r.rate,
            Amount: r.amount,
            "Bill Total": r.billTotal,
            Remarks: r.description
        })));

        const workbook = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(workbook, worksheet, "Sales Report");
        const excelBuffer = XLSX.write(workbook, { bookType: "xlsx", type: "array" });
        const blob = new Blob([excelBuffer], { type: "application/octet-stream" });
        saveAs(blob, `SalesReport_${fromDate}_to_${toDate}.xlsx`);
    };

    return (
        <div className="container mt-4">
            <h3 className="mb-3">Sales Report</h3>

            {/* Filters */}
            <div className="row g-2 mb-3">
                <div className="col-md-2">
                    <input
                        type="date"
                        className="form-control"
                        value={fromDate}
                        onChange={e => setFromDate(e.target.value)}
                    />
                </div>
                <div className="col-md-2">
                    <input
                        type="date"
                        className="form-control"
                        value={toDate}
                        onChange={e => setToDate(e.target.value)}
                    />
                </div>
                <div className="col-md-3">
                    <select
                        className="form-select"
                        value={customerId}
                        onChange={e => setCustomerId(e.target.value)}
                    >
                        <option value="">All Customers</option>
                        {customers.map(c => (
                            <option key={c.id} value={c.id}>{c.name}</option>
                        ))}
                    </select>
                </div>
                <div className="col-md-3">
                    <select
                        className="form-select"
                        value={itemId}
                        onChange={e => setItemId(e.target.value)}
                    >
                        <option value="">All Items</option>
                        {items.map(i => (
                            <option key={i.id} value={i.id}>{i.name}</option>
                        ))}
                    </select>
                </div>
                <div className="col-md-2 d-grid">
                    <button
                        className="btn btn-primary"
                        onClick={handleGenerate}
                        disabled={loading}
                    >
                        {loading ? "Generating..." : "Generate"}
                    </button>
                </div>
            </div>

            {/* Summary Cards */}
            {data.length > 0 && (
                <div className="row mb-3">
                    <div className="col-md-3">
                        <div className="card text-white bg-primary">
                            <div className="card-body">
                                <h6 className="card-title">Total Bills</h6>
                                <h4>{summary.totalBills}</h4>
                            </div>
                        </div>
                    </div>
                    <div className="col-md-3">
                        <div className="card text-white bg-success">
                            <div className="card-body">
                                <h6 className="card-title">Total Quantity</h6>
                                <h4>{summary.totalQuantity.toFixed(2)}</h4>
                            </div>
                        </div>
                    </div>
                    <div className="col-md-3">
                        <div className="card text-white bg-info">
                            <div className="card-body">
                                <h6 className="card-title">Total Amount</h6>
                                <h4>Rs. {summary.totalAmount.toFixed(2)}</h4>
                            </div>
                        </div>
                    </div>
                    <div className="col-md-3">
                        <div className="card text-white bg-warning">
                            <div className="card-body">
                                <h6 className="card-title">Average Bill</h6>
                                <h4>Rs. {summary.averageBillAmount.toFixed(2)}</h4>
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {/* Error Message */}
            {error && (
                <div className="alert alert-danger">{error}</div>
            )}

            {/* Export Buttons */}
            {data.length > 0 && (
                <div className="mb-3">
                    <button className="btn btn-danger me-2" onClick={exportPDF}>PDF</button>
                    <button className="btn btn-success me-2" onClick={exportExcel}>Excel</button>
                    <button className="btn btn-secondary" onClick={() => window.print()}>Print</button>
                </div>
            )}

            {/* Loading */}
            {loading && (
                <div className="text-center my-3">
                    <div className="spinner-border text-primary"></div>
                </div>
            )}

            {/* Table */}
            {!loading && data.length > 0 && (
                <>
                    <table className="table table-bordered table-striped">
                        <thead className="table-dark">
                            <tr>
                                <th>Date</th>
                                <th>Bill #</th>
                                <th>Customer</th>
                                <th>Item</th>
                                <th>Model</th>
                                <th className="text-end">Qty</th>
                                <th className="text-end">Rate</th>
                                <th className="text-end">Amount</th>
                                <th className="text-end">Bill Total</th>
                                <th>Remarks</th>
                            </tr>
                        </thead>
                        <tbody>
                            {currentRecords.map((row, index) => (
                                <tr key={index}>
                                    <td>{row.saleDate}</td>
                                    <td>{row.billNo}</td>
                                    <td>{row.customerName}</td>
                                    <td>{row.itemName}</td>
                                    <td>{row.modlNumb}</td>
                                    <td className="text-end">{row.quantity?.toFixed(2)}</td>
                                    <td className="text-end">{row.rate?.toFixed(2)}</td>
                                    <td className="text-end">{row.amount?.toFixed(2)}</td>
                                    <td className="text-end">{row.billTotal?.toFixed(2)}</td>
                                    <td>{row.description}</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>

                    {/* Pagination */}
                    {totalPages > 1 && (
                        <nav className="mt-3">
                            <ul className="pagination">
                                {[...Array(totalPages)].map((_, i) => (
                                    <li key={i}
                                        className={`page-item ${currentPage === i + 1 ? "active" : ""}`}>
                                        <button className="page-link"
                                            onClick={() => setCurrentPage(i + 1)}>
                                            {i + 1}
                                        </button>
                                    </li>
                                ))}
                            </ul>
                        </nav>
                    )}
                </>
            )}

            {!loading && data.length === 0 && !error && (
                <div className="alert alert-info">
                    No sales found for selected criteria.
                </div>
            )}
        </div>
    );
};

export default SalesReportPage;