import React, { useState, useEffect } from "react";
import {
    getPurchaseReturnReport,
    getSuppliers,
    getItems
} from "./purchaseReturnService";

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import { saveAs } from "file-saver";

const PurchaseReturnReportPage = () => {
    const [fromDate, setFromDate] = useState("");
    const [toDate, setToDate] = useState("");
    const [supplierId, setSupplierId] = useState("");
    const [itemId, setItemId] = useState("");

    const [suppliers, setSuppliers] = useState([]);
    const [items, setItems] = useState([]);
    const [data, setData] = useState([]);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState("");

    const [currentPage, setCurrentPage] = useState(1);
    const recordsPerPage = 10;

    // ================= LOAD DROPDOWNS =================
    useEffect(() => {
        loadDropdowns();
    }, []);

    const loadDropdowns = async () => {
        console.log("🔄 Loading dropdowns...");

        try {
            // Call APIs
            console.log("Calling getSuppliers...");
            const suppliersData = await getSuppliers();
            console.log("getSuppliers response:", suppliersData);

            console.log("Calling getItems...");
            const itemsData = await getItems();
            console.log("getItems response:", itemsData);

            // Set suppliers
            if (suppliersData && Array.isArray(suppliersData)) {
                console.log(`Setting ${suppliersData.length} suppliers`);
                setSuppliers(suppliersData);
            } else {
                console.log("No suppliers data or not array:", suppliersData);
                setSuppliers([]);
            }

            // Set items
            if (itemsData && Array.isArray(itemsData)) {
                console.log(`Setting ${itemsData.length} items`);
                setItems(itemsData);
            } else {
                console.log("No items data or not array:", itemsData);
                setItems([]);
            }

        } catch (err) {
            console.error("❌ Error in loadDropdowns:", err);
            setError("Failed to load filters");
        }
    };

    // ================= GENERATE REPORT =================
    const handleGenerate = async () => {
        if (!fromDate || !toDate) {
            alert("Select date range");
            return;
        }

        setLoading(true);
        setError("");

        try {
            const result = await getPurchaseReturnReport(
                fromDate,
                toDate,
                supplierId || null,
                itemId || null
            );

            setData(result || []);
            setCurrentPage(1);
        } catch (err) {
            setError(err.response?.data?.error || "Failed to generate report");
            console.error(err);
        } finally {
            setLoading(false);
        }
    };

    // ================= TOTALS =================
    const totalQuantity = data.reduce((sum, r) => sum + (Number(r.quantity) || 0), 0);
    const totalAmount = data.reduce((sum, r) => sum + (Number(r.amount) || 0), 0);

    // ================= PAGINATION =================
    const indexOfLast = currentPage * recordsPerPage;
    const indexOfFirst = indexOfLast - recordsPerPage;
    const currentRecords = data.slice(indexOfFirst, indexOfLast);
    const totalPages = Math.ceil(data.length / recordsPerPage);

    // ================= EXPORT PDF =================
    const exportPDF = () => {
        const doc = new jsPDF("landscape");
        const pageWidth = doc.internal.pageSize.getWidth();

        const companyName = "ABC Company Pvt Ltd";
        const branchName = "Main Branch";
        const loginUser = "admin";
        const generatedOn = new Date().toLocaleString();

        const supplierFilter = supplierId
            ? suppliers.find(s => s.id == supplierId)?.name || "Unknown"
            : "All Suppliers";
        const itemFilter = itemId
            ? items.find(i => i.id == itemId)?.name || "Unknown"
            : "All Items";

        // Header
        doc.setFontSize(18);
        doc.text(companyName, pageWidth / 2, 15, { align: "center" });
        doc.setFontSize(14);
        doc.text("Purchase Return Report", pageWidth / 2, 25, { align: "center" });

        doc.setFontSize(10);
        doc.text(`Branch: ${branchName}`, 14, 35);
        doc.text(`Date Range: ${fromDate} to ${toDate}`, 14, 42);
        doc.text(`Generated By: ${loginUser}`, 14, 49);
        doc.text(`Generated On: ${generatedOn}`, 14, 56);
        doc.text(`Supplier: ${supplierFilter}`, pageWidth - 14, 42, { align: "right" });
        doc.text(`Item: ${itemFilter}`, pageWidth - 14, 49, { align: "right" });

        // Table
        autoTable(doc, {
            startY: 65,
            head: [["Date", "Return #", "Supplier", "Item", "Model", "Qty", "Rate", "Amount", "Original Bill", "Remarks"]],
            body: data.map(r => [
                r.returnDate || "",
                r.returnBillNo || "",
                r.supplierName || "",
                r.itemName || "",
                r.modlNumb || "",
                (r.quantity || 0).toFixed(2),
                (r.rate || 0).toFixed(2),
                (r.amount || 0).toFixed(2),
                r.originalBillNo || "",
                r.description || ""
            ]),
            foot: [[
                "TOTALS", "", "", "", "",
                { content: totalQuantity.toFixed(2), styles: { halign: 'right' } },
                "",
                { content: totalAmount.toFixed(2), styles: { halign: 'right' } },
                "", ""
            ]],
            theme: "grid",
            styles: { fontSize: 8 },
            headStyles: { fillColor: [40, 40, 40] },
            footStyles: {
                fillColor: [40, 40, 40],
                textColor: [255, 255, 255],
                fontStyle: 'bold'
            },
            columnStyles: {
                5: { halign: 'right' },
                6: { halign: 'right' },
                7: { halign: 'right' },
            }
        });

        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.text(
                `Page ${i} of ${pageCount}`,
                pageWidth - 20,
                doc.internal.pageSize.getHeight() - 10
            );
        }

        doc.save(`PurchaseReturn_${fromDate}_to_${toDate}.pdf`);
    };

    // ================= EXPORT EXCEL =================
    const exportExcel = () => {
        const worksheet = XLSX.utils.json_to_sheet(data.map(r => ({
            Date: r.returnDate,
            "Return #": r.returnBillNo,
            Supplier: r.supplierName,
            Item: r.itemName,
            Model: r.modlNumb,
            Quantity: r.quantity,
            Rate: r.rate,
            Amount: r.amount,
            "Original Bill": r.originalBillNo,
            Remarks: r.description
        })));

        const workbook = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(workbook, worksheet, "Purchase Return");
        const excelBuffer = XLSX.write(workbook, { bookType: "xlsx", type: "array" });
        const blob = new Blob([excelBuffer], { type: "application/octet-stream" });
        saveAs(blob, `PurchaseReturn_${fromDate}_to_${toDate}.xlsx`);
    };

    return (
        <div className="container mt-4">
            <h3 className="mb-3">Purchase Return Report</h3>

            {/* Filters */}
            <div className="row g-2 mb-3">
                <div className="col-md-2">
                    <input
                        type="date"
                        className="form-control"
                        value={fromDate}
                        onChange={e => setFromDate(e.target.value)}
                    />
                </div>
                <div className="col-md-2">
                    <input
                        type="date"
                        className="form-control"
                        value={toDate}
                        onChange={e => setToDate(e.target.value)}
                    />
                </div>
                <div className="col-md-3">
                    <select
                        className="form-select"
                        value={supplierId}
                        onChange={e => setSupplierId(e.target.value)}
                    >
                        <option value="">All Suppliers</option>
                        {suppliers.map(s => (
                            <option key={s.id} value={s.id}>{s.name}</option>
                        ))}
                    </select>
                    {/* Debug: Show count */}
                    <small className="text-muted">
                        {suppliers.length} suppliers loaded
                    </small>
                </div>
                <div className="col-md-3">
                    <select
                        className="form-select"
                        value={itemId}
                        onChange={e => setItemId(e.target.value)}
                    >
                        <option value="">All Items</option>
                        {items.map(i => (
                            <option key={i.id} value={i.id}>{i.name}</option>
                        ))}
                    </select>
                    {/* Debug: Show count */}
                    <small className="text-muted">
                        {items.length} items loaded
                    </small>
                </div>
                <div className="col-md-2 d-grid">
                    <button
                        className="btn btn-primary"
                        onClick={handleGenerate}
                        disabled={loading}
                    >
                        {loading ? "Generating..." : "Generate"}
                    </button>
                </div>
            </div>

            {/* Debug Info Box */}
            <div className="alert alert-info small p-2 mb-2">
                <strong>Debug:</strong> Suppliers: {suppliers.length} | Items: {items.length}
                {suppliers.length > 0 && ` | First supplier: ${suppliers[0]?.name}`}
                {items.length > 0 && ` | First item: ${items[0]?.name}`}
                {error && ` | Error: ${error}`}
            </div>

            {/* Error Message */}
            {error && (
                <div className="alert alert-danger">{error}</div>
            )}

            {/* Export Buttons */}
            {data.length > 0 && (
                <div className="mb-3">
                    <button className="btn btn-danger me-2" onClick={exportPDF}>PDF</button>
                    <button className="btn btn-success me-2" onClick={exportExcel}>Excel</button>
                    <button className="btn btn-secondary" onClick={() => window.print()}>Print</button>
                </div>
            )}

            {/* Loading */}
            {loading && (
                <div className="text-center my-3">
                    <div className="spinner-border text-primary"></div>
                </div>
            )}

            {/* Table */}
            {!loading && data.length > 0 && (
                <>
                    <table className="table table-bordered table-striped">
                        <thead className="table-dark">
                            <tr>
                                <th>Date</th>
                                <th>Return #</th>
                                <th>Supplier</th>
                                <th>Item</th>
                                <th>Model</th>
                                <th className="text-end">Qty</th>
                                <th className="text-end">Rate</th>
                                <th className="text-end">Amount</th>
                                <th>Original Bill</th>
                                <th>Remarks</th>
                            </tr>
                        </thead>
                        <tbody>
                            {currentRecords.map((row, index) => (
                                <tr key={index}>
                                    <td>{row.returnDate}</td>
                                    <td>{row.returnBillNo}</td>
                                    <td>{row.supplierName}</td>
                                    <td>{row.itemName}</td>
                                    <td>{row.modlNumb}</td>
                                    <td className="text-end">{Number(row.quantity).toFixed(2)}</td>
                                    <td className="text-end">{Number(row.rate).toFixed(2)}</td>
                                    <td className="text-end">{Number(row.amount).toFixed(2)}</td>
                                    <td>{row.originalBillNo}</td>
                                    <td>{row.description}</td>
                                </tr>
                            ))}
                        </tbody>
                        <tfoot className="table-dark fw-bold">
                            <tr>
                                <td colSpan="5" className="text-end">TOTALS:</td>
                                <td className="text-end">{totalQuantity.toFixed(2)}</td>
                                <td className="text-end"></td>
                                <td className="text-end">{totalAmount.toFixed(2)}</td>
                                <td colSpan="2"></td>
                            </tr>
                        </tfoot>
                    </table>

                    {/* Pagination */}
                    {totalPages > 1 && (
                        <nav className="mt-3">
                            <ul className="pagination">
                                {[...Array(totalPages)].map((_, i) => (
                                    <li key={i}
                                        className={`page-item ${currentPage === i + 1 ? "active" : ""}`}>
                                        <button className="page-link"
                                            onClick={() => setCurrentPage(i + 1)}>
                                            {i + 1}
                                        </button>
                                    </li>
                                ))}
                            </ul>
                        </nav>
                    )}
                </>
            )}

            {!loading && data.length === 0 && !error && (
                <div className="alert alert-info">
                    No purchase returns found for selected criteria.
                </div>
            )}
        </div>
    );
};

export default PurchaseReturnReportPage;