//import React, { useRef, useState, useEffect } from "react";
//import { FaPrint, FaFileExcel, FaFilePdf, FaBuilding, FaCalendarAlt, FaUserClock } from "react-icons/fa";
//import * as XLSX from "xlsx";
//import axiosClient from "../../api/axiosClient";
//import "./Reports.css";

//export default function ReportTemplate({
//    title,
//    subtitle,
//    filters,
//    children,
//    printedBy = "System",
//    metaFields,

//}) {
//    const printRef = useRef();
//    const tableRef = useRef();
//    const cardsRef = useRef();
//    const [branchData, setBranchData] = useState({ name: "Main Branch", ntn: "", str: "" });

//    useEffect(() => { fetchBranchInfo(); }, []);

//    const fetchBranchInfo = async () => {
//        try {
//            const res = await axiosClient.get("/Branch/current");
//            const data = res.data?.data || res.data || {};
//            setBranchData({
//                name: data.branchName || data.name || "Main Branch",
//                ntn: data.ntn || data.NTN || "",
//                str: data.str || data.STR || ""
//            });
//        } catch (err) { console.log("Using default branch info"); }
//    };

//    const now = new Date();
//    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
//    const dateStr = `${String(now.getDate()).padStart(2, '0')}-${months[now.getMonth()]}-${now.getFullYear()}`;
//    const timeStr = now.toLocaleTimeString('en-PK', { hour: '2-digit', minute: '2-digit' });

//    // ============================================================
//    // PRINT / PDF — Professional Layout
//    // ============================================================
//    const handlePrint = () => {
//        const w = window.open("", "_blank");
//        const branch = branchData.name;
//        const ntn = branchData.ntn ? `NTN: ${branchData.ntn}` : "";
//        const str = branchData.str ? `STR: ${branchData.str}` : "";
//        const ntnLine = (ntn || str) ? `<div class="ph-sub">${ntn}${ntn && str ? ' | ' : ''}${str}</div>` : '';

//        const tableHTML = tableRef.current?.outerHTML || "";
//        const cardsHTML = cardsRef.current?.outerHTML || "";

//        w.document.write(`<!DOCTYPE html><html><head><title>${title}</title><style>
//            @page{size:A4;margin:10mm 12mm}
//            *{margin:0;padding:0;box-sizing:border-box}
//            body{font-family:'Segoe UI',Arial,sans-serif;font-size:11px;color:#1a1a1a;line-height:1.4}
//            .ph{display:flex;justify-content:space-between;align-items:center;padding-bottom:10px;margin-bottom:12px;border-bottom:2px solid #1a1a1a}
//            .ph-l h1{font-size:16px;font-weight:700;color:#1a1a1a;margin-bottom:2px}
//            .ph-sub{font-size:8px;color:#555}
//            .ph-r{text-align:right;font-size:8px;color:#777}
//            .ph-r .ph-label{font-size:7px;text-transform:uppercase;letter-spacing:2px;color:#999;margin-bottom:2px}
//            .pt{text-align:center;font-size:15px;font-weight:700;padding:8px 0;margin-bottom:10px;border-top:1px solid #1a1a1a;border-bottom:1px solid #1a1a1a;letter-spacing:1px}

//            /* ✅ NEW: Left-Right Info Cards */
//            .pi{display:flex;gap:20px;margin-bottom:12px;border:1px solid #ccc;padding:8px 12px}
//            .pi-col{flex:1}
//            .pi-row{display:flex;justify-content:space-between;padding:4px 0;border-bottom:1px dotted #ddd;font-size:10px}
//            .pi-row:last-child{border-bottom:none}
//            .pi-label{font-weight:600;color:#555;min-width:100px}
//            .pi-value{text-align:right;color:#1a1a1a;font-weight:700}

//            table{width:100%;border-collapse:collapse;margin:8px 0;font-size:10px}
//            th{background:#e8e8e8;color:#1a1a1a;border:1px solid #999;padding:6px 8px;text-align:left;font-weight:700;font-size:9px;text-transform:uppercase;letter-spacing:.3px}
//            td{border:1px solid #ccc;padding:5px 8px}
//            .tr{text-align:right}.tc{text-align:center}
//            .tfr td{font-weight:700;background:#f0f0f0;border-top:2px solid #1a1a1a}
//            .pf{margin-top:15px;padding-top:8px;border-top:1px solid #999;display:flex;justify-content:space-between;font-size:8px;color:#888}
//        </style></head><body>
//            <div class="ph">
//                <div class="ph-l"><h1>${branch}</h1>${ntnLine}</div>
//                <div class="ph-r"><div class="ph-label">REPORT</div><div>${dateStr}</div><div>${timeStr}</div></div>
//            </div>
//            <div class="pt">${title}</div>
//            ${cardsHTML}
//            ${tableHTML}
//            <div class="pf"><div>Generated by: ${printedBy}</div><div>${dateStr} ${timeStr}</div></div>
//        </body></html>`);
//        w.document.close();
//        setTimeout(() => w.print(), 300);
//    };

//    const handleExcel = () => {
//        const table = tableRef.current;
//        if (table) {
//            const wb = XLSX.utils.table_to_book(table);
//            XLSX.writeFile(wb, `${title.replace(/\s/g, '_')}.xlsx`);
//        }
//    };

//    return (
//        <div className="report-premium">
//            {filters && <div className="rp-filters no-print">{filters}</div>}

//            <div className="rp-actions no-print">
//                <div className="rp-actions-left"><span className="rp-generated">Generated: {dateStr} {timeStr}</span></div>
//                <div className="rp-actions-right">
//                    <button className="rp-btn rp-btn-print" onClick={handlePrint}><FaPrint /> Print</button>
//                    <button className="rp-btn rp-btn-pdf" onClick={handlePrint}><FaFilePdf /> PDF</button>
//                    <button className="rp-btn rp-btn-excel" onClick={handleExcel}><FaFileExcel /> Excel</button>
//                </div>
//            </div>

//            <div className="rp-content" ref={printRef}>
//                {/* SCREEN HEADER */}
//                <div className="rp-header-clean screen-only">
//                    <div className="rp-header-left">
//                        <div className="rp-branch-icon"><FaBuilding /></div>
//                        <div className="rp-header-info">
//                            <h2>{branchData.name}</h2>
//                            {(branchData.ntn || branchData.str) && (
//                                <div className="rp-header-ntn">
//                                    {branchData.ntn ? `NTN: ${branchData.ntn}` : ''}
//                                    {branchData.ntn && branchData.str ? ' | ' : ''}
//                                    {branchData.str ? `STR: ${branchData.str}` : ''}
//                                </div>
//                            )}
//                            <div className="rp-header-meta">
//                                <span><FaCalendarAlt /> {dateStr}</span>
//                                <span className="rp-dot">•</span>
//                                <span><FaUserClock /> {timeStr}</span>
//                            </div>
//                        </div>
//                    </div>
//                    <div className="rp-header-right">
//                        <div className="rp-report-label">REPORT</div>
//                    </div>
//                </div>

//                {/* TITLE */}
//                <div className="rp-title-clean">{title}</div>
//                {subtitle && <div className="rp-subtitle-clean">{subtitle}</div>}

//                {/* INFO CARDS — Screen: Grid, Print: Left-Right */}
//                {metaFields && (
//                    <>
//                        {/* Screen View */}
//                        <div className="rp-info-cards-clean screen-only">
//                            {metaFields.map((f, i) => (
//                                <div key={i} className="rp-info-card-clean">
//                                    <div className="label">{f.label}</div>
//                                    <div className="value">{f.value}</div>
//                                </div>
//                            ))}
//                        </div>
//                        {/* Print View */}
//                        <div className="rp-info-print print-only" ref={cardsRef}>
//                            <div className="pi">
//                                <div className="pi-col">
//                                    {metaFields.filter((_, i) => i % 2 === 0).map((f, i) => (
//                                        <div key={i} className="pi-row">
//                                            <span className="pi-label">{f.label}</span>
//                                            <span className="pi-value">{f.value}</span>
//                                        </div>
//                                    ))}
//                                </div>
//                                <div className="pi-col">
//                                    {metaFields.filter((_, i) => i % 2 === 1).map((f, i) => (
//                                        <div key={i} className="pi-row">
//                                            <span className="pi-label">{f.label}</span>
//                                            <span className="pi-value">{f.value}</span>
//                                        </div>
//                                    ))}
//                                </div>
//                            </div>
//                        </div>
//                    </>
//                )}

//                {/* TABLE */}
//                <div ref={tableRef}>
//                    {children}
//                </div>

//                {/* SCREEN FOOTER */}
//                <div className="rp-footer-clean screen-only">
//                    <div>Generated by: {printedBy}</div>
//                    <div>{dateStr} {timeStr}</div>
//                </div>
//            </div>
//        </div>
//    );
//}

import React, { useRef, useState, useEffect } from "react";
import { FaPrint, FaFileExcel, FaFilePdf, FaBuilding, FaCalendarAlt, FaUserClock } from "react-icons/fa";
import * as XLSX from "xlsx";
import axiosClient from "../../api/axiosClient";
import "./Reports.css";

export default function ReportTemplate({
    title,
    subtitle,
    filters,
    children,
    printedBy = "System",
    metaFields,
    extraActions,  // 👈 ADD THIS - for custom export buttons
}) {
    const printRef = useRef();
    const tableRef = useRef();
    const cardsRef = useRef();
    const [branchData, setBranchData] = useState({ name: "Main Branch", ntn: "", str: "" });

    useEffect(() => { fetchBranchInfo(); }, []);

    const fetchBranchInfo = async () => {
        try {
            const res = await axiosClient.get("/Branch/current");
            const data = res.data?.data || res.data || {};
            setBranchData({
                name: data.branchName || data.name || "Main Branch",
                ntn: data.ntn || data.NTN || "",
                str: data.str || data.STR || ""
            });
        } catch (err) { console.log("Using default branch info"); }
    };

    const now = new Date();
    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    const dateStr = `${String(now.getDate()).padStart(2, '0')}-${months[now.getMonth()]}-${now.getFullYear()}`;
    const timeStr = now.toLocaleTimeString('en-PK', { hour: '2-digit', minute: '2-digit' });

    // ============================================================
    // PRINT / PDF — Professional Layout
    // ============================================================
    const handlePrint = () => {
        const w = window.open("", "_blank");
        const branch = branchData.name;
        const ntn = branchData.ntn ? `NTN: ${branchData.ntn}` : "";
        const str = branchData.str ? `STR: ${branchData.str}` : "";
        const ntnLine = (ntn || str) ? `<div class="ph-sub">${ntn}${ntn && str ? ' | ' : ''}${str}</div>` : '';

        const tableHTML = tableRef.current?.outerHTML || "";
        const cardsHTML = cardsRef.current?.outerHTML || "";

        w.document.write(`<!DOCTYPE html><html><head><title>${title}</title><style>
            @page{size:A4;margin:10mm 12mm}
            *{margin:0;padding:0;box-sizing:border-box}
            body{font-family:'Segoe UI',Arial,sans-serif;font-size:11px;color:#1a1a1a;line-height:1.4}
            .ph{display:flex;justify-content:space-between;align-items:center;padding-bottom:10px;margin-bottom:12px;border-bottom:2px solid #1a1a1a}
            .ph-l h1{font-size:16px;font-weight:700;color:#1a1a1a;margin-bottom:2px}
            .ph-sub{font-size:8px;color:#555}
            .ph-r{text-align:right;font-size:8px;color:#777}
            .ph-r .ph-label{font-size:7px;text-transform:uppercase;letter-spacing:2px;color:#999;margin-bottom:2px}
            .pt{text-align:center;font-size:15px;font-weight:700;padding:8px 0;margin-bottom:10px;border-top:1px solid #1a1a1a;border-bottom:1px solid #1a1a1a;letter-spacing:1px}
            
            /* Info Cards */
            .pi{display:flex;gap:20px;margin-bottom:12px;border:1px solid #ccc;padding:8px 12px}
            .pi-col{flex:1}
            .pi-row{display:flex;justify-content:space-between;padding:4px 0;border-bottom:1px dotted #ddd;font-size:10px}
            .pi-row:last-child{border-bottom:none}
            .pi-label{font-weight:600;color:#555;min-width:100px}
            .pi-value{text-align:right;color:#1a1a1a;font-weight:700}
            
            table{width:100%;border-collapse:collapse;margin:8px 0;font-size:10px}
            th{background:#e8e8e8;color:#1a1a1a;border:1px solid #999;padding:6px 8px;text-align:left;font-weight:700;font-size:9px;text-transform:uppercase;letter-spacing:.3px}
            td{border:1px solid #ccc;padding:5px 8px}
            .tr{text-align:right}.tc{text-align:center}
            .tfr td{font-weight:700;background:#f0f0f0;border-top:2px solid #1a1a1a}
            .pf{margin-top:15px;padding-top:8px;border-top:1px solid #999;display:flex;justify-content:space-between;font-size:8px;color:#888}
        </style></head><body>
            <div class="ph">
                <div class="ph-l"><h1>${branch}</h1>${ntnLine}</div>
                <div class="ph-r"><div class="ph-label">REPORT</div><div>${dateStr}</div><div>${timeStr}</div></div>
            </div>
            <div class="pt">${title}</div>
            ${cardsHTML}
            ${tableHTML}
            <div class="pf"><div>Generated by: ${printedBy}</div><div>${dateStr} ${timeStr}</div></div>
        </body></html>`);
        w.document.close();
        setTimeout(() => w.print(), 300);
    };

    const handleExcel = () => {
        const table = tableRef.current;
        if (table) {
            const wb = XLSX.utils.table_to_book(table);
            XLSX.writeFile(wb, `${title.replace(/\s/g, '_')}.xlsx`);
        }
    };

    return (
        <div className="report-premium">
            {filters && <div className="rp-filters no-print">{filters}</div>}

            <div className="rp-actions no-print">
                <div className="rp-actions-left"><span className="rp-generated">Generated: {dateStr} {timeStr}</span></div>
                <div className="rp-actions-right">
                    {/* 👇 CUSTOM EXPORT BUTTONS (from PurchaseReport) */}
                    {extraActions && <div className="rp-extra-actions">{extraActions}</div>}
                    <button className="rp-btn rp-btn-print" onClick={handlePrint}><FaPrint /> Print</button>
                    <button className="rp-btn rp-btn-pdf" onClick={handlePrint}><FaFilePdf /> PDF</button>
                    <button className="rp-btn rp-btn-excel" onClick={handleExcel}><FaFileExcel /> Excel</button>
                </div>
            </div>

            <div className="rp-content" ref={printRef}>
                {/* SCREEN HEADER */}
                <div className="rp-header-clean screen-only">
                    <div className="rp-header-left">
                        <div className="rp-branch-icon"><FaBuilding /></div>
                        <div className="rp-header-info">
                            <h2>{branchData.name}</h2>
                            {(branchData.ntn || branchData.str) && (
                                <div className="rp-header-ntn">
                                    {branchData.ntn ? `NTN: ${branchData.ntn}` : ''}
                                    {branchData.ntn && branchData.str ? ' | ' : ''}
                                    {branchData.str ? `STR: ${branchData.str}` : ''}
                                </div>
                            )}
                            <div className="rp-header-meta">
                                <span><FaCalendarAlt /> {dateStr}</span>
                                <span className="rp-dot">•</span>
                                <span><FaUserClock /> {timeStr}</span>
                            </div>
                        </div>
                    </div>
                    <div className="rp-header-right">
                        <div className="rp-report-label">REPORT</div>
                    </div>
                </div>

                {/* TITLE */}
                <div className="rp-title-clean">{title}</div>
                {subtitle && <div className="rp-subtitle-clean">{subtitle}</div>}

                {/* INFO CARDS — Screen: Grid, Print: Left-Right */}
                {metaFields && (
                    <>
                        {/* Screen View */}
                        <div className="rp-info-cards-clean screen-only">
                            {metaFields.map((f, i) => (
                                <div key={i} className="rp-info-card-clean">
                                    <div className="label">{f.label}</div>
                                    <div className="value">{f.value}</div>
                                </div>
                            ))}
                        </div>
                        {/* Print View */}
                        <div className="rp-info-print print-only" ref={cardsRef}>
                            <div className="pi">
                                <div className="pi-col">
                                    {metaFields.filter((_, i) => i % 2 === 0).map((f, i) => (
                                        <div key={i} className="pi-row">
                                            <span className="pi-label">{f.label}</span>
                                            <span className="pi-value">{f.value}</span>
                                        </div>
                                    ))}
                                </div>
                                <div className="pi-col">
                                    {metaFields.filter((_, i) => i % 2 === 1).map((f, i) => (
                                        <div key={i} className="pi-row">
                                            <span className="pi-label">{f.label}</span>
                                            <span className="pi-value">{f.value}</span>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </div>
                    </>
                )}

                {/* TABLE */}
                <div ref={tableRef}>
                    {children}
                </div>

                {/* SCREEN FOOTER */}
                <div className="rp-footer-clean screen-only">
                    <div>Generated by: {printedBy}</div>
                    <div>{dateStr} {timeStr}</div>
                </div>
            </div>
        </div>
    );
}