import React, { useState, useEffect } from "react";
import {
    getPurchaseDetail,
    getSuppliers,
    getItems
} from "./purchaseReportService";

import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import { saveAs } from "file-saver";

const PurchaseDetailReportPage = () => {

    const [fromDate, setFromDate] = useState("");
    const [toDate, setToDate] = useState("");

    const [supplierId, setSupplierId] = useState("");
    const [itemId, setItemId] = useState("");

    const [suppliers, setSuppliers] = useState([]);
    const [items, setItems] = useState([]);

    const [data, setData] = useState([]);
    const [loading, setLoading] = useState(false);

    const [currentPage, setCurrentPage] = useState(1);
    const recordsPerPage = 10;

    useEffect(() => {
        loadDropdowns();
    }, []);

    const loadDropdowns = async () => {
        const branchId = 1;
        const supplierData = await getSuppliers(branchId);
        const itemData = await getItems(branchId);
        setSuppliers(supplierData);
        setItems(itemData);
    };

    const handleGenerate = async () => {
        if (!fromDate || !toDate) {
            alert("Select date range");
            return;
        }

        setLoading(true);

        const result = await getPurchaseDetail(
            fromDate,
            toDate,
            supplierId || null,
            itemId || null
        );

        setData(result);
        setCurrentPage(1);
        setLoading(false);
    };

    // 🔥 Totals
    const qtyTotal = data.reduce((sum, r) => sum + (r.purcQnty || 0), 0);
    const rateTotal = data.reduce((sum, r) => sum + (r.purcRate || 0), 0);
    const amountTotal = data.reduce((sum, r) => sum + (r.purcAmnt || 0), 0);

    // 🔥 Pagination
    const indexOfLast = currentPage * recordsPerPage;
    const indexOfFirst = indexOfLast - recordsPerPage;
    const currentRecords = data.slice(indexOfFirst, indexOfLast);
    const totalPages = Math.ceil(data.length / recordsPerPage);

    // 🔥 PDF Export
    //const exportPDF = () => {
    //    const doc = new jsPDF();
    //    doc.text("Purchase Detail Report", 14, 15);

    //    autoTable(doc, {
    //        startY: 20,
    //        head: [["Bill", "Date", "Supplier", "Item", "Model", "Qty", "Rate", "Amount"]],
    //        body: data.map(r => [
    //            r.billNumb,
    //            r.tranDate?.substring(0, 10),
    //            r.supplierName,
    //            r.itemName,
    //            r.modlNumb,
    //            r.purcQnty,
    //            r.purcRate,
    //            r.purcAmnt
    //        ])
    //    });

    //    doc.save("PurchaseDetailReport.pdf");
    //};
    const exportPDF = () => {

        const doc = new jsPDF("landscape");
        const pageWidth = doc.internal.pageSize.getWidth();

        const branchName = "Main Branch";
        const loginUser = "admin";
        const generatedOn = new Date().toLocaleString();

        const supplierFilter = supplierId
            ? suppliers.find(s => s.id == supplierId)?.name
            : "All Suppliers";

        const itemFilter = itemId
            ? items.find(i => i.id == itemId)?.name
            : "All Items";

        // ===== HEADER =====
        doc.setFontSize(18);
        doc.text("ABC Company Pvt Ltd", pageWidth / 2, 15, { align: "center" });

        doc.setFontSize(14);
        doc.text("Purchase Detail Report", pageWidth / 2, 25, { align: "center" });

        doc.setFontSize(10);
        doc.text(`Branch: ${branchName}`, 14, 35);
        doc.text(`Date Range: ${fromDate} to ${toDate}`, 14, 42);
        doc.text(`Generated By: ${loginUser}`, 14, 49);
        doc.text(`Generated On: ${generatedOn}`, 14, 56);

        doc.text(`Supplier Filter: ${supplierFilter}`, pageWidth - 14, 42, { align: "right" });
        doc.text(`Item Filter: ${itemFilter}`, pageWidth - 14, 49, { align: "right" });

        // ===== TABLE =====
        autoTable(doc, {
            startY: 65,
            head: [["Bill", "Date", "Supplier", "Item", "Model", "Qty", "Rate", "Amount"]],
            body: data.map(r => [
                r.billNumb,
                r.tranDate?.substring(0, 10),
                r.supplierName,
                r.itemName,
                r.modlNumb,
                r.purcQnty?.toFixed(2),
                r.purcRate?.toFixed(2),
                r.purcAmnt?.toFixed(2)
            ]),
            foot: [[
                "TOTALS", "", "", "", "",
                qtyTotal.toFixed(2),
                rateTotal.toFixed(2),
                amountTotal.toFixed(2)
            ]],
            theme: "grid",
            styles: {
                fontSize: 8
            },
            headStyles: {
                fillColor: [40, 40, 40]
            }
        });

        // ===== PAGE NUMBER =====
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.text(
                `Page ${i} of ${pageCount}`,
                pageWidth - 20,
                doc.internal.pageSize.getHeight() - 10
            );
        }

        doc.save("PurchaseDetailReport.pdf");
    };

    // 🔥 Excel Export
    const exportExcel = () => {
        const worksheet = XLSX.utils.json_to_sheet(data);
        const workbook = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(workbook, worksheet, "Report");
        const excelBuffer = XLSX.write(workbook, { bookType: "xlsx", type: "array" });
        const blob = new Blob([excelBuffer], { type: "application/octet-stream" });
        saveAs(blob, "PurchaseDetailReport.xlsx");
    };

    return (
        <div className="container mt-4">
            <h3 className="mb-3">Purchase Detail Report</h3>

            {/* Filters */}
            <div className="row g-2 mb-3">
                <div className="col-md-2">
                    <input type="date" className="form-control"
                        value={fromDate}
                        onChange={e => setFromDate(e.target.value)} />
                </div>

                <div className="col-md-2">
                    <input type="date" className="form-control"
                        value={toDate}
                        onChange={e => setToDate(e.target.value)} />
                </div>

                <div className="col-md-3">
                    <select className="form-select"
                        value={supplierId}
                        onChange={e => setSupplierId(e.target.value)}>
                        <option value="">All Suppliers</option>
                        {suppliers.map(s => (
                            <option key={s.id} value={s.id}>{s.name}</option>
                        ))}
                    </select>
                </div>

                <div className="col-md-3">
                    <select className="form-select"
                        value={itemId}
                        onChange={e => setItemId(e.target.value)}>
                        <option value="">All Items</option>
                        {items.map(i => (
                            <option key={i.id} value={i.id}>{i.name}</option>
                        ))}
                    </select>
                </div>

                <div className="col-md-2 d-grid">
                    <button className="btn btn-primary" onClick={handleGenerate}>
                        Generate
                    </button>
                </div>
            </div>

            {/* Export Buttons */}
            <div className="mb-3">
                <button className="btn btn-danger me-2" onClick={exportPDF}>PDF</button>
                <button className="btn btn-success me-2" onClick={exportExcel}>Excel</button>
                <button className="btn btn-secondary" onClick={() => window.print()}>Print</button>
            </div>

            {/* Loading */}
            {loading && (
                <div className="text-center my-3">
                    <div className="spinner-border text-primary"></div>
                </div>
            )}

            {/* Table */}
            {!loading && (
                <>
                    <table className="table table-bordered table-striped">
                        <thead className="table-dark">
                            <tr>
                                <th>Bill</th>
                                <th>Date</th>
                                <th>Supplier</th>
                                <th>Item</th>
                                <th>Model</th>
                                <th>Qty</th>
                                <th>Rate</th>
                                <th>Amount</th>
                            </tr>
                        </thead>
                        <tbody>
                            {currentRecords.map((row, index) => (
                                <tr key={index}>
                                    <td>{row.billNumb}</td>
                                    <td>{row.tranDate?.substring(0, 10)}</td>
                                    <td>{row.supplierName}</td>
                                    <td>{row.itemName}</td>
                                    <td>{row.modlNumb}</td>
                                    <td>{row.purcQnty}</td>
                                    <td>{row.purcRate}</td>
                                    <td>{row.purcAmnt}</td>
                                </tr>
                            ))}
                        </tbody>
                        <tfoot className="table-light fw-bold">
                            <tr>
                                <td colSpan="5" className="text-end">Totals:</td>
                                <td>{qtyTotal.toFixed(2)}</td>
                                <td>{rateTotal.toFixed(2)}</td>
                                <td>{amountTotal.toFixed(2)}</td>
                            </tr>
                        </tfoot>
                    </table>

                    {/* Pagination */}
                    <nav>
                        <ul className="pagination">
                            {[...Array(totalPages)].map((_, i) => (
                                <li key={i}
                                    className={`page-item ${currentPage === i + 1 ? "active" : ""}`}>
                                    <button className="page-link"
                                        onClick={() => setCurrentPage(i + 1)}>
                                        {i + 1}
                                    </button>
                                </li>
                            ))}
                        </ul>
                    </nav>
                </>
            )}
        </div>
    );
};

export default PurchaseDetailReportPage;
